jobs:
  train-job:
    name: ML MLOps Light Job
    tasks:
      - task_key: train_model
        description: "Train diabetes regression model"
        new_cluster:
          spark_version: 13.3.x-scala2.12
          num_workers: 0
          node_type_id: Standard_DS3_v2  # 💡 plus petit nœud possible sur Azure
          data_security_mode: SINGLE_USER
          runtime_engine: STANDARD        # ❌ Pas PHOTON (plus coûteux)
        spark_python_task:
          python_file: /Workspace/Users/anass.b.compt@gmail.com/.bundle/mlops-train-job/default/files/src/train.py
