jobs:
  train-job:
    name: ML MLOps Serverless Job (Bundle)
    tasks:
      - task_key: train_model
        description: "Train diabetes regression model"
        new_cluster:
          spark_version: 13.3.x-scala2.12
          num_workers: 1
          data_security_mode: SINGLE_USER
          runtime_engine: PHOTON
        spark_python_task:
          python_file: dbfs:/FileStore/train.py 