name: Deploy and Run Databricks Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  deploy-and-run-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Databricks CLI (v2)
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI version
        run: databricks version

      - name: Configure Databricks CLI authentication
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databrickscfg
          [DEFAULT]
          host = ${{ secrets.DATABRICKS_HOST }}
          token = ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Validate Databricks Bundle
        run: databricks bundle validate

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy
