# .github/workflows/deploy.yml
name: Deploy ML to Databricks

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Upload train.py to DBFS
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_INSTANCE }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks fs cp train.py dbfs:/FileStore/train.py

      - name: Deploy to Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_INSTANCE: ${{ secrets.DATABRICKS_INSTANCE }}
        run: bash deploy_databricks.sh

