# .github/workflows/deploy.yml
name: Deploy ML to Databricks

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t abouirdi/mlops-databricks-demo:latest .
          docker push abouirdi/mlops-databricks-demo:latest

      - name: Deploy to Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_INSTANCE: ${{ secrets.DATABRICKS_INSTANCE }}
        run: bash deploy_databricks.sh

