name: Upload to Databricks DBFS

on:
  push:
    branches:
      - main

jobs:
  upload-to-dbfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Add Databricks CLI path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Upload train.py to DBFS
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_INSTANCE }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks fs cp train.py dbfs:/FileStore/train.py --overwrite
