name: Deploy and Run Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy-and-run-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Databricks CLI (v2)
        uses: databricks/setup-cli@v1

      - name: Check Databricks CLI version
        run: databricks version

      - name: Configure Databricks CLI auth
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks auth login --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN"

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy
