name: Deploy and Run Databricks Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-and-run-bundle:
    runs-on: ubuntu-latest

    env:  # 👈 AUTH via ENV VARS (recommandé)
      DATABRICKS_HOST: https://${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Databricks CLI (v2)
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI version
        run: databricks version

      - name: Validate Databricks Bundle
        run: databricks bundle validate

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy
